development:
    dialect: postgres
    datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} port=${DB_PORT} sslmode=${DB_SSL_MODE}
    dir: db/migrations
    table: migrations
